// Code generated by goctl. DO NOT EDIT!
// Source: chat.proto

package server

import (
	"context"

	"github.com/heyehang/go-im-grpc/chat_server"
	"go-im-chat-server/internal/logic"
	"go-im-chat-server/internal/svc"
)

type ChatServer struct {
	svcCtx *svc.ServiceContext
	chat_server.UnimplementedChatServer
}

func NewChatServer(svcCtx *svc.ServiceContext) *ChatServer {
	return &ChatServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatServer) CreateChat(ctx context.Context, in *chat_server.CreateChatReq) (*chat_server.CreateChatResp, error) {
	l := logic.NewCreateChatLogic(ctx, s.svcCtx)
	return l.CreateChat(in)
}

func (s *ChatServer) RecentChats(ctx context.Context, in *chat_server.RecentChatsReq) (*chat_server.RecentChatsResp, error) {
	l := logic.NewRecentChatsLogic(ctx, s.svcCtx)
	return l.RecentChats(in)
}

func (s *ChatServer) JoinToChat(ctx context.Context, in *chat_server.JoinToChatReq) (*chat_server.EmptyResp, error) {
	l := logic.NewJoinToChatLogic(ctx, s.svcCtx)
	return l.JoinToChat(in)
}

func (s *ChatServer) RemoveMemberFromChat(ctx context.Context, in *chat_server.RemoveMemberFromChatReq) (*chat_server.EmptyResp, error) {
	l := logic.NewRemoveMemberFromChatLogic(ctx, s.svcCtx)
	return l.RemoveMemberFromChat(in)
}

func (s *ChatServer) GetChatMsgList(ctx context.Context, in *chat_server.GetChatMsgListReq) (*chat_server.GetChatMsgListResp, error) {
	l := logic.NewGetChatMsgListLogic(ctx, s.svcCtx)
	return l.GetChatMsgList(in)
}

func (s *ChatServer) GetMemberList(ctx context.Context, in *chat_server.GetMemberListReq) (*chat_server.GetMemberListResp, error) {
	l := logic.NewGetMemberListLogic(ctx, s.svcCtx)
	return l.GetMemberList(in)
}
